# Create a new folder inside lesson-4 called assignment-4 and start working on this assignment from there!

# Working with the code examples in the lesson 4 notes create your own image by building up patterns of pixels using the modulo operator and other techniques from those examples. Try 2-3 versions of this and make sure the output images are saved in your assignment-4 folder and labelled accordingly. 
from PIL import Image
import sys


img = Image.new("RGB", (400, 400), "blue")
for y in range(400):
    for x in range(400):
        pixel = (x % 255, y % 255, (x + y) % 255)
        img.putpixel((x, y), pixel)
img.save("newrandomimage.jpg")

# Now create your own image by collaging together at least 4 different images specified on the command line. Try to bring in some pattern and transparency techniques from lesson 4 notes. Try 2-3 versions of this and make sure the output images are saved in your assignment-4 folder and labelled accordingly. 

# * for this assignment you should have two files, for example part1.py and part2.py and at least 4 images (generated by your code files) all saved in your unit-1/lesson-4/assignment-4 folder plus the original images you used as data!